name: artifact-evaluation
run-name: ${{ inputs.task }} / ${{ inputs.optionDisplayName }}
on:
  workflow_dispatch:
    inputs:
      task:
        type: choice
        required: true
        options:
          - fig6
          - fig8
          - fig9
          - fig10
          - fig11
      option:
        type: string
        required: true
      optionDisplayName:
        type: string
        required: true
jobs:
  fig6:
    if: ${{ inputs.task == 'fig6' }}
    runs-on: [self-hosted, ae-server]
    env:
      OPTION: ${{ inputs.option }}
    steps:
      - uses: actions/checkout@v6
      - name: Link models
        run: bash scripts/link_models.sh
      - name: Run fig6
        run: bash scripts/fig6.sh
  fig8:
    if: ${{ inputs.task == 'fig8' }}
    runs-on: [self-hosted, ae-machine]
    env:
      OPTION: ${{ inputs.option }}
    defaults:
      run:
        working-directory: STM/
    steps:
      - uses: actions/checkout@v6
      - name: Reset USB devices
        run: bash scripts/reset_usb.sh
      - name: Patch repository root
        run: bash scripts/patch_repo_root.sh
      - name: Run fig8
        run: bash scripts/fig8/fig8.sh
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: results
          path: STM/results/
  fig9:
    if: ${{ inputs.task == 'fig9' }}
    runs-on: [self-hosted, ae-server]
    env:
      OPTION: ${{ inputs.option }}
    steps:
      - uses: actions/checkout@v6
      - name: Link models
        run: bash scripts/link_models.sh
      - name: Run fig9
        run: bash scripts/fig9.sh
  fig10:
    if: ${{ inputs.task == 'fig10' }}
    runs-on: [self-hosted, ae-server]
    env:
      OPTION: ${{ inputs.option }}
    steps:
      - uses: actions/checkout@v6
      - name: Link models
        run: bash scripts/link_models.sh
      - name: Run fig10
        run: bash scripts/fig10.sh
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: results
          path: DupNAS/HEtest/allseed_report_summary_*.csv
  fig11:
    if: ${{ inputs.task == 'fig11' }}
    runs-on: [self-hosted, ae-machine]
    env:
      OPTION: ${{ inputs.option }}
    defaults:
      run:
        working-directory: STM/
    steps:
      - uses: actions/checkout@v6
      - name: Reset USB devices
        run: bash scripts/reset_usb.sh
      - name: Patch repository root
        run: bash scripts/patch_repo_root.sh
      - name: Gather TFLM memory usage
        if: ${{ contains(inputs.option, 'tflm') }}
        run: bash scripts/gather_tflm_mem.sh
      - name: Run fig11
        run: bash scripts/fig11/fig11.sh
      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: results
          path: STM/results/
